In [2]:
from itertools import cycle
import numpy as np

#!pip install plotly -q
#import plotly.express as px

In [3]:
raw_inp = """59791911701697178620772166487621926539855976237879300869872931303532122404711706813176657053802481833015214226705058704017099411284046473395211022546662450403964137283487707691563442026697656820695854453826690487611172860358286255850668069507687936410599520475680695180527327076479119764897119494161366645257480353063266653306023935874821274026377407051958316291995144593624792755553923648392169597897222058613725620920233283869036501950753970029182181770358827133737490530431859833065926816798051237510954742209939957376506364926219879150524606056996572743773912030397695613203835011524677640044237824961662635530619875905369208905866913334027160178"""
A = "12345678"

In [4]:
def parse_input(raw):
    return [int(c) for c in raw]

inp = parse_input(A)
inp

[1, 2, 3, 4, 5, 6, 7, 8]

## Part 1

The input is some numbers, all single digits.

In [5]:
base_pattern = [0, 1, 0, -1]
len(base_pattern)
[i for i in range(4)]

[0, 1, 2, 3]

In [17]:
i = 0; size=8
base = cycle(base_pattern)
x = np.ravel([[next(base)] * (i + 1) for _ in range(size+1)])[1:size+1]
print(x)

np.tile(np.repeat(base_pattern, 1), 2)

[ 1  0 -1  0  1  0 -1  0]


array([ 0,  1,  0, -1,  0,  1,  0, -1])

In [18]:
def make_pattern(inp):
    size = len(inp)
    pattern = np.zeros((size,size), dtype="int32")
    
    # make grid to solve
    for i in range(size):
        base = cycle(base_pattern)
        x = np.ravel([[next(base)] * (i + 1) for _ in range(size+1)])[1:size+1]
        x = np.tile(np.repeat(base_pattern, i+1), 3)[1:9]
        pattern[i] = x
    return pattern    
inp = parse_input(A)
make_pattern(A)

array([[ 1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1]], dtype=int32)

In [19]:
def make_pattern(inp):
    size = len(inp)
    pattern = np.zeros((size,size), dtype="int32")
    
    # make grid to solve
    for i in range(size):
        base = cycle(base_pattern)
        x = np.ravel([[next(base)] * (i + 1) for _ in range(size+1)])[1:size+1]
        pattern[i] = x
    return pattern    
inp = parse_input(A)
make_pattern(A)

array([[ 1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1]], dtype=int32)

In [6]:
def make_pattern(inp):
    size = len(inp)
    pattern = np.zeros((size,size), dtype="int32")
    
    # make grid to solve
    for i in range(size):
        base = cycle(base_pattern)
        x = np.ravel([[next(base)] * (i + 1) for _ in range(size+1)])[1:size+1]
        pattern[i] = x
    return pattern    
inp = parse_input(A)
make_pattern(A)

array([[ 1,  0, -1,  0,  1,  0, -1,  0],
       [ 0,  1,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  1]], dtype=int32)

In [ ]:
def solve_1(raw, phases=100):
    inp = parse_input(raw)
    pattern = make_pattern(inp)

    # do the stuff
    for _ in range(phases):
        inp = np.dot(pattern, inp)
        # get the first digit of the abs value
        inp = np.mod(np.abs(inp), 10)
        
    return "".join([str(i) for i in inp[:8]])
    
assert solve_1(A, 4) == "01029498"

A2 = "80871224585914546619083218645595"
assert solve_1(A2) == "24176176"

A3 = "19617804207202209144916044189917"
assert solve_1(A3) == "73745418"

A4 = "69317163492948606335995924319873"
assert solve_1(A4) == "52432133"

In [ ]:
%%time
solve_1(raw_inp)

CPU times: user 12.6 s, sys: 36 ms, total: 12.6 s
Wall time: 12.6 s


'45834272'

In [ ]:
inp = parse_input(A) * 2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]