In [56]:
import re
from typing import NamedTuple

import matplotlib.pyplot as plt
import numpy as np
import utils

## Day 4: Giant Squid

[#](https://adventofcode.com/2021/day/4) We're playing bingo on a `5x5` board with a giant squad.

So we have:

* a list of boards with random numbers in a `5x5` grid
* random numbers drawn one a time, after which on each board the numbers are marked off.
* the winner is the first board with a complete row or column of marked numbers.
* the score is the sum of all unmarked numbers times the last number called.

In [144]:
test: str = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
"""

inp = utils.get_input(4)

In [150]:
def parse(inp=test, verbose=False):
    data = inp.splitlines()
    draw = [int(n) for n in data[0].split(",")]

    boards = []
    board = []
    for i, row in enumerate(data[2:]):
        if len(row) > 2:
            board.append([int(i) for i in row.split(" ") if i.isdigit()])

        if len(board) == 5:
            boards.append(board.copy())
            board = []

    return draw, np.array(boards)


draw, boards = parse(inp)

In [165]:
def solve(inp=test, verbose: bool = False):
    draw, boards = parse(inp)
    bingo = np.zeros_like(boards, dtype=bool)

    for num in draw:
        # print(num)
        ma = np.ma.masked_where(boards == num, boards).mask
        bingo += ma

        for i, b in enumerate(bingo):
            # check for bingo in rows and cols
            if any(np.all(b == True, axis=0)) or any(np.all(b == True, axis=1)):
                print(
                    f"board {i} \n{np.ma.masked_array(boards[i], ~b)}\n is the winner"
                )

                unmasked_sum = np.ma.masked_array(boards[i], b).sum()
                print(f"{unmasked_sum=} {num=}")
                return unmasked_sum * num

    print("Something went wrong if you're here...")
    return None


assert solve(test) == 4512  # example answer
solve(inp)

board 2 
[[14 21 17 24 4]
 [-- -- -- 9 --]
 [-- -- 23 -- --]
 [-- 11 -- -- 5]
 [2 0 -- -- 7]]
 is the winner
unmasked_sum=188 num=24
board 69 
[[69 29 -- -- 76]
 [4 83 64 33 2]
 [-- 81 -- -- --]
 [-- -- -- 15 8]
 [-- -- -- 12 --]]
 is the winner
unmasked_sum=624 num=4


2496

## Part 2

We're scared enough of the giant squid that we want to loose by picking the board which will win last.

Figure out the final board and its score.

In [169]:
def solve_2(inp=test, verbose: bool = False):
    draw, boards = parse(inp)
    bingo = np.zeros_like(boards, dtype=bool)

    winning_boards = []

    for num in draw:
        # print(num)
        ma = np.ma.masked_where(boards == num, boards).mask
        bingo += ma

        for i, b in enumerate(bingo):
            # check for bingo in rows and cols
            if any(np.all(b == True, axis=0)) or any(np.all(b == True, axis=1)):
                if i not in winning_boards:
                    winning_boards.append(i)

                if len(winning_boards) == len(boards):
                    unmasked_sum = np.ma.masked_array(boards[i], b).sum()

                    print(
                        f"board {i} at {num=}\n{np.ma.masked_array(boards[i], ~b)}\n is the winner"
                    )
                    print(f"{unmasked_sum=} {num=}")
                    return unmasked_sum * num

    print("Something went wrong if you're here...")
    return None


assert solve_2(test) == 1924  # example answer
solve_2(inp)

board 1 at num=13
[[-- -- 0 2 --]
 [9 -- 13 17 5]
 [-- -- 7 -- 23]
 [-- 11 10 24 4]
 [14 21 16 -- --]]
 is the winner
unmasked_sum=148 num=13
board 19 at num=61
[[69 51 -- -- --]
 [90 61 91 6 21]
 [-- -- 81 -- 49]
 [67 -- -- 96 17]
 [78 11 -- 64 77]]
 is the winner
unmasked_sum=425 num=61


25925