In [4]:
import utils
import math
import re
import itertools
from typing import NamedTuple
from collections import defaultdict, deque
import itertools

import numpy as np

import matplotlib.pyplot as plt

## Day 17: Conway Cubes

[#](https://adventofcode.com/2020/day/17). We have an infinite 3d grid, every integer coordinate `x,y,z` can be active or inactive.

We start off with a small 2d initial state in this 3d universe, which boots up by doing 6 cycles. The rules are:

- active cubes with 2 or 3 active neighbours remain active, else they become inactive.
- inactive cubes with 3 active neighbours become active.

Every cube has 26 neighbours.

In [3]:
test17 = """.#.
..#
###"""

#inp17 = utils.get_input(6, splitlines=False)

test17

'.#.\n..#\n###'

To represent the grid, I'm going to use numpy:

In [81]:
def parse_17(inp=test17, padding=100):
    inp = inp.splitlines()

    width = len(inp[0]) + padding 
    height = len(inp) + padding

    grid = np.zeros((3,height, width), dtype="int")

    for y, row in enumerate(inp):
        y += padding // 2
        for x, char in enumerate(row):
            x += padding // 2
            grid[1][y, x] = 1 if char == "#" else 0

    return grid

grid = parse_17()
grid[1][48:55,48:55]

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

First up, a simple function to return the neighbours.

In [82]:
print(inp)

['.#.', '..#', '###']


In [103]:
grid[0:2, 1:8, 4:8]

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [153]:
point = (51,50,1)
x, y, z = point
print(z, y, x, point)
grid[1,50, 51], grid[z,y,x]

1 50 51 (51, 50, 1)


(1, 1)

In [155]:
def count_neighbours(point, grid=grid, verbose=False):
    """counts all the neighbours"""
    x, y, z = point
    z_min, z_max = max(0, z-1), min(3, z+2)
    if verbose: print(grid[z_min:z_max, y-1:y+2, x-1:x+2], grid[z,y,x])
    # we minus the point itself as its not a neighbour to itself
    return grid[z_min:z_max, y-1:y+2, x-1:x+2].sum() - grid[z,y,x]
    
count_neighbours(point=(51,50,1), verbose=True)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] 1


1

In [133]:
def get_neighbours(point):
    x, y, z = point
    return [(x2, y2 , z2) for 
            x2 in range(x-1, x+2) for 
            y2 in range(y-1, y+2) for
            z2 in range(z-1, z+2) if (x2, y2, z2) != point]

neighbours = get_neighbours(point=(1,51,51))

print(neighbours)

[(0, 50, 50), (0, 50, 51), (0, 50, 52), (0, 51, 50), (0, 51, 51), (0, 51, 52), (0, 52, 50), (0, 52, 51), (0, 52, 52), (1, 50, 50), (1, 50, 51), (1, 50, 52), (1, 51, 50), (1, 51, 52), (1, 52, 50), (1, 52, 51), (1, 52, 52), (2, 50, 50), (2, 50, 51), (2, 50, 52), (2, 51, 50), (2, 51, 51), (2, 51, 52), (2, 52, 50), (2, 52, 51), (2, 52, 52)]


In [7]:
def parse_6(inp=test6, verbose=False):
    return [n for n in inp.splitlines()]

data = parse_6()

In [9]:
def solve_6(inp=test6):
    pass
    
assert solve_6() == None
solve_6(inp6)

## Part 2



So that should be straightforward:

In [4]:
def solve_6b(inp=test6):
    pass
    
#assert solve_6b() == 6
solve_6b()